[package]
name = "smolasm"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotnetdll = { path = "../.." }
pest = "2.7"
pest_derive = "2.7"
