[package]
name = "smolasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotnetdll = { path = ".." }
pest = "2.2.1"
pest_derive = "2.2.1"
